config/routes.rb
Rails.application.routes.draw do
  resources :licenses
  resources :subscriptions
  resources :plans
  resources :products
  resources :distributors
  resources :users
  apipie
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distributor.rb
class Distributor < ApplicationRecord
end

app/models/license.rb
class License < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/distributors_controller.rb
class DistributorsController < InheritedResources::Base

  private

    def distributor_params
      params.require(:distributor).permit(:email)
    end

end

app/controllers/licenses_controller.rb
class LicensesController < InheritedResources::Base

  #private

  def license_params
    params.require(:license).permit(:idSubskrypcji, :idProduktu)
  end
  api :GET, '/licenses/:id', "Zwraca podstawowe informacje o licencji"
  def wow
  end

  api :GET, '/licenses', "Zwraca wszystkie licencje zalgowanego dystrybutora"
  def prefex
  end

  api :DELETE, '/licenses/:id', "Usuwa licencje"
  def kieroy
  end

end

app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base

  private

    def plan_params
      params.require(:plan).permit(:Nazwa, :Cena, :CzasTrwania, :DarmowyOkres, :idProduktu, :IloscLicencji)
    end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  #private

  def product_params
    params.require(:product).permit(:Nazwa)
  end
  api :GET, '/products/:id', "zwraca podstawowe informacje o produkcie"
  def wow
  end

  api :GET, '/products', "zwraca produkty zalogowanego dystrybutora"
  def prefex
  end

  api :DELETE, '/products/:id', "Usuwa produkt"
  def kieroy
  end


end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < InheritedResources::Base

  #private

  def subscription_params
    params.require(:subscription).permit(:idKlienta, :idPlanu)
  end
  api :GET, '/v1/subscriptions/:id', "Zwraca podstawowe informacje o subskrypcji"
  def wow
  end

  api :GET, '/v1/subscriptions', "Zwraca subskrypcje zalogowanego dystrybutora"
  def prefex
  end

  api :POST, '/v1/subscriptions', "Tworzy subskrypcje"
  param :subscription, Hash, desc: "Subscription data" do
    param :idPlanu, Integer,  :required => true
    param :idKlienta, String,  :required => true
  end
  def kate
  end

  api :DELETE, '/subscriptions/:id', "Usuwa subskrypcje"
  def kieroy
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def user_params
    params.require(:user).permit(:email, :imie, :nazwisko, :nrtel)
  end
  api :GET, '/users/:id', "Zwraca podstawowe informacje o kliencie"
  def wow
  end

  api :GET, '/v1/users', "Zwraca klientow zalogowanego dystrybutora"
  def prefex
  end

  api :PUT, '/v1/users/:id', "Aktualizuje dane klienta"
  param :id, String, required: true
  param :user, Hash, desc: "User data" do
    param :email, String,  :required => false
    param :imie, String,  :required => false
    param :nazwisko, String,  :required => false
    param :nrtel, String,  :required => false
  end
  def popdate
  end

  api :GET, '/v1/users/:id/licenses', "Zwraca licencje przypisane do klienta"
  param :id, String, required: true
  def show_licenses
  end

  api :GET, '/v1/users/:id/subscriptions', "Zwraca subskrypcje przypisane do klienta"
  param :id, String, required: true
  def show_subscriptions
  end

  api :DELETE, '/users/:id', "Usuwa klienta"
  def kieroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/distributors/_form.html.erb
<%= form_with(model: distributor, local: true) do |form| %>
  <% if distributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
      <% distributor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<h1>Editing Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Show', @distributor %> |
<%= link_to 'Back', distributors_path %>

app/views/distributors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributors</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributors.each do |distributor| %>
      <tr>
        <td><%= distributor.email %></td>
        <td><%= link_to 'Show', distributor %></td>
        <td><%= link_to 'Edit', edit_distributor_path(distributor) %></td>
        <td><%= link_to 'Destroy', distributor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distributor', new_distributor_path %>

app/views/distributors/new.html.erb
<h1>New Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Back', distributors_path %>

app/views/distributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @distributor.email %>
</p>

<%= link_to 'Edit', edit_distributor_path(@distributor) %> |
<%= link_to 'Back', distributors_path %>

app/views/licenses/_form.html.erb
<%= form_with(model: license, local: true) do |form| %>
  <% if license.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(license.errors.count, "error") %> prohibited this license from being saved:</h2>

      <ul>
      <% license.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idSubskrypcji %>
    <%= form.number_field :idSubskrypcji %>
  </div>

  <div class="field">
    <%= form.label :idProduktu %>
    <%= form.number_field :idProduktu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/licenses/edit.html.erb
<h1>Editing License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Show', @license %> |
<%= link_to 'Back', licenses_path %>

app/views/licenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Licenses</h1>

<table>
  <thead>
    <tr>
      <th>Idsubskrypcji</th>
      <th>Idproduktu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.idSubskrypcji %></td>
        <td><%= license.idProduktu %></td>
        <td><%= link_to 'Show', license %></td>
        <td><%= link_to 'Edit', edit_license_path(license) %></td>
        <td><%= link_to 'Destroy', license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New License', new_license_path %>

app/views/licenses/new.html.erb
<h1>New License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Back', licenses_path %>

app/views/licenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idsubskrypcji:</strong>
  <%= @license.idSubskrypcji %>
</p>

<p>
  <strong>Idproduktu:</strong>
  <%= @license.idProduktu %>
</p>

<%= link_to 'Edit', edit_license_path(@license) %> |
<%= link_to 'Back', licenses_path %>

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nazwa %>
    <%= form.text_field :Nazwa %>
  </div>

  <div class="field">
    <%= form.label :Cena %>
    <%= form.number_field :Cena %>
  </div>

  <div class="field">
    <%= form.label :CzasTrwania %>
    <%= form.number_field :CzasTrwania %>
  </div>

  <div class="field">
    <%= form.label :DarmowyOkres %>
    <%= form.number_field :DarmowyOkres %>
  </div>

  <div class="field">
    <%= form.label :idProduktu %>
    <%= form.number_field :idProduktu %>
  </div>

  <div class="field">
    <%= form.label :IloscLicencji %>
    <%= form.number_field :IloscLicencji %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Cena</th>
      <th>Czastrwania</th>
      <th>Darmowyokres</th>
      <th>Idproduktu</th>
      <th>Ilosclicencji</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.Nazwa %></td>
        <td><%= plan.Cena %></td>
        <td><%= plan.CzasTrwania %></td>
        <td><%= plan.DarmowyOkres %></td>
        <td><%= plan.idProduktu %></td>
        <td><%= plan.IloscLicencji %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @plan.Nazwa %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @plan.Cena %>
</p>

<p>
  <strong>Czastrwania:</strong>
  <%= @plan.CzasTrwania %>
</p>

<p>
  <strong>Darmowyokres:</strong>
  <%= @plan.DarmowyOkres %>
</p>

<p>
  <strong>Idproduktu:</strong>
  <%= @plan.idProduktu %>
</p>

<p>
  <strong>Ilosclicencji:</strong>
  <%= @plan.IloscLicencji %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nazwa %>
    <%= form.text_field :Nazwa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.Nazwa %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @product.Nazwa %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idKlienta %>
    <%= form.number_field :idKlienta %>
  </div>

  <div class="field">
    <%= form.label :idPlanu %>
    <%= form.number_field :idPlanu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Idklienta</th>
      <th>Idplanu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.idKlienta %></td>
        <td><%= subscription.idPlanu %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idklienta:</strong>
  <%= @subscription.idKlienta %>
</p>

<p>
  <strong>Idplanu:</strong>
  <%= @subscription.idPlanu %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :imie %>
    <%= form.text_field :imie %>
  </div>

  <div class="field">
    <%= form.label :nazwisko %>
    <%= form.text_field :nazwisko %>
  </div>

  <div class="field">
    <%= form.label :nrtel %>
    <%= form.text_field :nrtel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Nrtel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.imie %></td>
        <td><%= user.nazwisko %></td>
        <td><%= user.nrtel %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Imie:</strong>
  <%= @user.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @user.nazwisko %>
</p>

<p>
  <strong>Nrtel:</strong>
  <%= @user.nrtel %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>